### ISSUE TITLE
Text Highlighting in Files

### ISSUE THREAD

**Issue by Shahriarnz14** [ninerealmlabs/jupyterlab-theme-material-night-eighties#12]
The text highlighting in the notebook seem fine as the background of cells are slightly brighter than the highlighted text. But in files (e.g. *.py files) the background is dark and the highlighting of selected text is not visible at all.

**Comment by ahgraber** [comment]
I believe I fixed this in the most recent version (0.2.10), but please let me know

<img width="1189" alt="Screen Shot 2022-04-12 at 13 29 24" src="https://user-images.githubusercontent.com/24922003/163020200-dd464b93-b5b1-41c2-85f1-c3dda627d1b4.png">

<img width="1188" alt="Screen Shot 2022-04-12 at 13 29 41" src="https://user-images.githubusercontent.com/24922003/163020211-729ae3d9-fafe-4721-bf8a-553b87ad2236.png">
